docs: updating createPaymentMethod params
stripe/stripe-react-native pull request #1050
Opened 2022-07-19 10:08 UTC by vivekvardhanadepu

## Summary

## Motivation

## Testing

- [ ] I tested this manually
- [ ] I added automated tests

## Documentation

Select one: 
- [ ] I have added relevant documentation for my changes.
- [ ] This PR does not result in any developer-facing changes.

2022-07-19 10:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stripe/stripe-react-native?pullRequest=1050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stripe/stripe-react-native?pullRequest=1050) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stripe/stripe-react-native?pullRequest=1050) it.</sub>

2022-07-19 16:22 UTC, charliecruzan-stripe requested changes
thanks for catching this! can you also change L287 and L288 to:

```
  paymentMethodType: 'Card',
  paymentMethodData: {
    billingDetails,
  },
  ```

2022-07-19 16:22 UTC, charliecruzan-stripe commented on docs/tipsi-stripe-migration-guide.md
> +  paymentMethodType: 'Card',
```suggestion
  paymentMethodType: 'Card',
  paymentMethodData: {
    billingDetails: {
      email: 'email@stripe.com',
    }, // optional
  },
```

2022-07-19 21:02 UTC, charliecruzan-stripe requested changes
can you also change L287 and L288 to:

```
  paymentMethodType: 'Card',
  paymentMethodData: {
    billingDetails,
  },
```

2022-07-20 05:02 UTC, vivekvardhanadepu commented
> can you also change L287 and L288 to:
> 
> ```
>   paymentMethodType: 'Card',
>   paymentMethodData: {
>     billingDetails,
>   },
> ```

you mean in confirmSetupIntent?

2022-07-20 16:51 UTC, charliecruzan-stripe approved these changes
will merge once the CLA is signed :)

2022-07-22 18:25 UTC, vivekvardhanadepu commented
> will merge once the CLA is signed :)

Done

2022-07-22 18:26 UTC, merged