fix: 'when' expression must be exhaustive. Kotlin 1.7.10
stripe/stripe-react-native pull request #1195
Opened 2022-11-10 00:27 UTC by ffedelefrsf

fix: 'when' expression must be exhaustive, add necessary 'UpiAwaitNotification' branch or 'else' branch instead

When upgrading Kotlin version to 1.7.10, this error show up. So an 'else' condition is added in order to make the library compile again. It could easily be another specific case that contemplates 'UpiAwaitNotification' as well.

## Summary
When upgrading Kotlin version to 1.7.10, this error show up. So an 'else' condition is added in order to make the library compile again. It could easily be another specific case that contemplates 'UpiAwaitNotification' as well.

## Motivation
I believe this is a needed change for the library compatibility with Kotlin 1.7.10 new version. At least it was necessary for my project to build again.

## Testing
- [ x ] I tested this manually
- [ ] I added automated tests

## Documentation

Select one: 
- [ x ] I have added relevant documentation for my changes.
- [ ] This PR does not result in any developer-facing changes.

2022-11-10 00:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stripe/stripe-react-native?pullRequest=1195) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stripe/stripe-react-native?pullRequest=1195) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stripe/stripe-react-native?pullRequest=1195) it.</sub>

2022-11-10 18:41 UTC, charliecruzan-stripe requested changes
let's add an explicit case for this instead. It makes it easy to catch new `NextActionType` in the future 🔍

2022-11-10 18:41 UTC, charliecruzan-stripe commented on android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt
> +    }
```suggestion
    NextActionType.BlikAuthorize, NextActionType.UseStripeSdk, NextActionType.UpiAwaitNotification,  null -> {
      return null
    }
```

2022-11-11 21:51 UTC, justinadkins commented
Thank you @ffedelefrsf! I'm experiencing this issue as well. Our dirty hack until now:
```groovy
allprojects { project ->
    ...
    if (project.name.contains("stripe-react-native")) {
        tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach { t ->
            kotlinOptions {
                freeCompilerArgs += "-XXLanguage:-ProhibitNonExhaustiveWhenOnAlgebraicTypes"
            }
        }
    }
}
```

2022-11-15 16:52 UTC, charliecruzan-stripe commented
Tests are failing for an unrelated reason, have it fixed on a feature branch so merging this. thanks @ffedelefrsf !

2022-11-15 16:52 UTC, merged