WIP: Google pay android implementation
stripe/stripe-react-native pull request #441
Opened 2021-07-20 17:26 UTC by arekkubaczkowski

2021-07-23 14:55 UTC, ustkirill commented
Hi guys!

Your package very useful, but I need google pay also, I tried use other packages, but it's not work. Do you have any time estimate for this PR?

Can I help with anything? :)

2021-07-23 15:02 UTC, jaaywags commented
> Can I help with anything? :)

Yes, I am happy to help too anywhere I can. Thanks!

2021-07-27 16:48 UTC, thorsten-stripe requested changes
Some nits regarding the button

2021-07-27 16:48 UTC, thorsten-stripe commented on docs/GooglePay.md
> +      <Button
Let's link to https://developers.google.com/pay/api/android/guides/brand-guidelines for reference on how to style the button

2021-07-27 16:48 UTC, thorsten-stripe commented on example/src/screens/GooglePayScreen.tsx
> +      <Button
Style button based on https://developers.google.com/pay/api/android/guides/brand-guidelines

2021-07-27 16:48 UTC, thorsten-stripe commented on example/src/screens/GooglePayScreen.tsx
> +      <Button
![image](https://user-images.githubusercontent.com/23213994/127194373-7606dbb8-7b70-45db-98d6-cc5045edde59.png)

2021-07-27 16:48 UTC, thorsten-stripe commented on example/src/screens/GooglePayScreen.tsx
> +          title="Crete payment method"
Use basic Gpay button without text https://developers.google.com/pay/api/android/guides/brand-guidelines

![image](https://user-images.githubusercontent.com/23213994/127194436-f01b3b6f-8fe3-4beb-9433-5a19b1936f74.png)

2021-07-28 15:21 UTC, thorsten-stripe approved these changes
LGTM, thanks

2021-07-30 09:44 UTC, merged

2021-07-30 11:48 UTC, fredriksormo commented
When will google pay be available in the expo version of this package?

2021-08-02 03:44 UTC, thorsten-stripe commented
> When will google pay be available in the expo version of this package?

It will be available from Expo SDK 43 onward which is slotted for release in October.