feat: add affirm payment method
stripe/stripe-react-native pull request #825
Opened 2022-02-23 01:18 UTC by jameswoo-stripe

## Summary

- Add Affirm payment method bindings
- Add Affirm payment method to example app
- Update example server to handle item ids and prices, this was needed because affirm requires a minimum of $USD 50

|  iOS | Android  |
|---|---|
| https://user-images.githubusercontent.com/99316447/155246874-30e37dfb-4936-4dca-9974-7257110e10f4.mov  | https://user-images.githubusercontent.com/99316447/155246905-7d7c30cb-ea2d-4389-be23-6047e815c738.mov  |

## Testing

- [x] I tested this manually
- [ ] I added automated tests

## Documentation

Select one: 
- [ ] I have added relevant documentation for my changes.
- [ ] This PR does not result in any developer-facing changes.

2022-02-23 01:23 UTC, jameswoo-stripe commented on android/build.gradle
> +  maven { url 'https://jitpack.io' }
This will be removed and the gradle dependency will be corrected

2022-02-23 01:23 UTC, jameswoo-stripe commented on example/android/app/build.gradle
> +    // implementation 'com.stripe:stripe-wechatpay:17.1.0'
This change will be removed, just need this temporarily to build correctly if testing locally.

2022-02-23 01:23 UTC, jameswoo-stripe commented on example/ios/Podfile
> +  pod 'StripeCore', :git => 'https://github.com/stripe-ios/stripe-ios.git', :branch => 'private'
This will be removed, used for testing locally

2022-02-23 16:10 UTC, charliecruzan-stripe requested changes
this is really great 🎉 just a couple nits is all from me. 

As for testing- for some reason, the Afterpay test was disabled before I got here, my guess is it's just flaky, but let's try adding one for affirm. It can be done in the same file right below [the afterpay test](https://github.com/stripe/stripe-react-native/blob/master/e2e/paymentsWithRedirects.test.ts#L156-L164), and it'll look super similar

2022-07-08 23:13 UTC, charliecruzan-stripe commented
replaced by https://github.com/stripe/stripe-react-native/pull/1036

2022-07-08 23:13 UTC, closed without merging